# Generated by Django 4.1.3 on 2022-11-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra_app', '0005_userfeedback_bmicalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmicalculator',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
