import Head from 'next/head'
import {useRef, useEffect, useState} from 'react'
import { useImageUpload } from '../src/hooks/useImageUpload';
import axios from 'axios';

export default function Home() {
  const imgFile = useRef();
  const {uploadImg, fruitName} = useImageUpload();
  const [search, setSearch] = useState("");
  const [fruitId, setFruitId] = useState("");
  const [isSearch, setIsSearch] = useState(false);

  const fetchNutriValue = async () => {
    await axios.get(`http://192.168.93.33:8000/api/calorie-detail/${fruitId}`)
        .then((res) => {
            console.log(res.data);
        })
        .catch((err) => {
            if(err.response){
                console.log(err.response.data);
                console.log(err.response.status);
                console.log(err.response.headers);
            }else if(err.request){
                console.log(err.request);
            }else{
                console.log("Error: ", err.message);
            }
            console.log(err.config);
        })
  }

  const handleSearch = async () => {
    await axios.get(`http://192.168.93.33:8000/api/search-fruits/?ordering=-id&search=${search}`)
        .then((res) => {
            console.log(res.data);
            setFruitId(res.data.results[0].id)
            setIsSearch(!isSearch);
        })
        .catch((err) => {
            if(err.response){
                console.log(err.response.data);
                console.log(err.response.status);
                console.log(err.response.headers);
            }else if(err.request){
                console.log(err.request);
            }else{
                console.log("Error: ", err.message);
            }
            console.log(err.config);
        })
  }

  const handleClick = () => {
    uploadImg(imgFile.current.files[0]);
  }

  useEffect(() => {
    if(isSearch){
      fetchNutriValue()
      setIsSearch(!isSearch)
    }
  },[isSearch])

  useEffect(()=>{console.log(fruitName)},[fruitName]);

  return (
    <div className="w-full cont">
      <Head>
        <title>Nutra</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      
      <div 
      className='search py-[1rem] flex flex-row items-center justify-center gap-[0.3rem] w-full'>

        <input 
        className='rounded-[5rem] px-[1rem] py-[0.6rem] outline-none bg-secon text-light-Shade flex-1' 
        type="text" 
        onChange={e => {setSearch(e.target.value)}}
        placeholder='Enter fruit name' 
        />

        <button 
        className='rounded-[5rem] bg-main py-[0.6rem] text-light px-[1.5rem] active:scale-90'
        onClick={handleSearch}
        >search</button>
      </div>

      <div className="w-[25rem] my-4 flex items-center justify-center h-[25rem] bg-image-upload rounded-[1rem] bg-center"></div>

      <input type="file" ref={imgFile}/>
      <button type="submit" onClick={handleClick}>Upload</button>

      <div id='about' className="h-[10rem] w-full my-4 bg-white">hello</div>
      
    </div>
  )
}
